### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by graham-willis-druid** [DEFRA/rod-licensing#86]
(1) It would be useful I think to have some step by step documentation on how to run the sales API locally. The dynamics library requires a set environment variables yet these variables are actually required by the client of the library - the sales API.
I think a guide for local running in the top level README would be useful as much of the information is distributed.
(2) The OAUTH_HOST requires a trailing backslash https://login.microsoftonline.com/ for the system to start. This is probably a gotcha that is best removed.

**Comment by sgardnerdell** [comment]
Point 1 has been addressed.

Point 2 has been resolved by migrating from adal-node to simple-oauth2
